#!/usr/bin/python3

import argparse
import sys
import os
import re
from collections import OrderedDict

class Reference:
    """An entry of reference, entire message, author, year, page"""
    

    def __init__ (self, filename, linenumber):
        self.from_file_ = filename
        self.from_line_ = linenumber
        self.ref_type_ = ""
        self.all_ref_ = ""
        self.author_ = ""
        self.year_ = ""
        self.page_ = ""
        self.eid_ = ""
        self.error_ = ""
        self.key_  = ""

    def has_complete_data(self):
        if not self.author_:
            self.error_ = self.error_ + "No auther found! "
        if not self.year_:
            self.error_ = self.error_ + "No year found! "
        if not self.page_:
            if not self.eid_:
                self.error_ = self.error_ + "No page found! "
            else:
                self.page_ = self.eid_
        if self.error_:
            return False
        else:
            return True


    def record(self, line):
        self.all_ref_ = self.all_ref_ + line

    def record_new_ref(self, line):
        message = re.sub('{.+,', '{LABEL_TBD,', line, re.IGNORECASE)
        self.all_ref_ = message

    def set_ref_type(self, line):
        message = re.search(r"[\w]+", line)
        if message:
            self.ref_type_ = message.group().lower()

    def set_author(self, line):
        message = re.sub('author *= *', '', line, re.IGNORECASE)
        message = re.sub(',.*', '', message, re.IGNORECASE)
        message = re.sub('and.*', '', message, re.IGNORECASE)
        message = re.sub('\\\\.', '', message, re.IGNORECASE)
        message = re.findall(r"\S+", message)[-1]
        all_letters = re.findall('\w', message)
        self.author_ = ''.join(all_letters)

    def set_year(self, line):
        message = re.search(r"[0-9]+", line)
        if message:
            self.year_ = message.group()

    def set_page(self, line):
        message = re.sub('-.*', '', line, re.IGNORECASE)
        message = re.search(r"[0-9]+", message)
        if message:
            self.page_ = message.group()

    def set_eid(self, line):
        message = re.sub('-.*', '', line, re.IGNORECASE)
        message = re.search(r"[0-9]+", message)
        if message:
            self.eid_ = message.group()

    def set_key(self, line):
        self.key_ = line
        self.all_ref_ = re.sub('LABEL_TBD', line, self.all_ref_, re.IGNORECASE)

    def is_new_err_ref(self):
        if self.all_ref_ not in seen_err_ref_list:
            seen_err_ref_list.append(self.all_ref_)
            return True
        else:
            return False


class InputLine:
    """A line from the input file"""
    
    data = ""
    n_brackets = 0

    def __init__ (self, string, read):
        self.data = string
        self.n_brackets = read.n_brackets

    def is_new_ref (self):
        if (re.search('@', self.data, re.IGNORECASE) and self.n_brackets == 0):
            return True
        else:
            return False
    
    def is_ref (self):
        if (self.n_brackets > 0):
            return True
        else:
            return False
    
    def is_end_of_ref (self):
        nbra = re.findall('{', self.data)
        nket = re.findall('}', self.data)
        current_n_brackets = self.n_brackets + len(nbra) - len(nket)
        if (current_n_brackets == 0):
            return True
        else:
            return False
    
    def is_garbage (self):
        if (self.n_brackets == 0):
            return True
        else:
            return False

    def is_author(self):
        if re.search('author *=', self.data, re.IGNORECASE):
            return True
        else:
            return False

    def is_year(self):
        if (re.search('year *=', self.data, re.IGNORECASE)):
            return True
        else:
            return False

    def is_page(self):
        if (re.search('(?<!num)pages *=', self.data, re.IGNORECASE)):
            return True
        else:
            return False

    def is_eid(self):
        if (re.search('(?<!num)eid *=', self.data, re.IGNORECASE)):
            return True
        else:
            return False


class Read:
    """record data from all input files"""
    
    def __init__ (self, args):
        self.n_brackets = 0
        for file_name in args[0:]:
            if not self.read_from_file(file_name):
                print("File {} does not exist. Exiting..".format(file_name))
                sys.exit()


    def read_from_file(self, file_name):
        global ref_list 
        global incomplete_ref_list
        global dictionary
        global seen_err_ref_list

        if not os.path.isfile(file_name):
            print("File {} does not exist. Exiting..".format(file_name))
            sys.exit()
    
        line_number = 0;
        self.n_brackets = 0;
        with open(file_name, 'r') as infile:
            readline = infile.readline()
            while readline:
                line = InputLine(readline, self)
                line_number += 1
                if line.is_new_ref():
                    current_ref = Reference(file_name, line_number)
                    current_ref.record_new_ref(line.data)
                    current_ref.set_ref_type(line.data)
                    self.count_brackets(line.data)
                    if line.is_end_of_ref():
                        incomplete_ref_list.append(current_ref)
                elif line.is_ref():
                    if line.is_author():
                        current_ref.set_author(line.data)
                    if line.is_page():
                        current_ref.set_page(line.data)
                    if line.is_eid():
                        current_ref.set_eid(line.data)
                    if line.is_year():
                        current_ref.set_year(line.data)
                    current_ref.record(line.data)
                    self.count_brackets(line.data)
                    if line.is_end_of_ref():
                        if current_ref.ref_type_ == 'book':
                            current_ref.page_ = 'book'
                        if current_ref.has_complete_data():
                            key = current_ref.author_ + ":" + current_ref.year_ + ":" + current_ref.page_
                            value = current_ref
                            current_ref.set_key(key)
                            if (key not in dictionary):
                                dictionary[key] = value
                                ref_list.append(current_ref)
                        else:
                            if current_ref.is_new_err_ref():
                                incomplete_ref_list.append(current_ref)
                elif line.is_garbage():
                    self.count_brackets(line.data)
                else:
                    self.n_brackets = 0
                    # The original code would complain is there are extra } in the input file. But bibtex ignores
                    # the extra }s, so I should do the same
                    #try:
                    #    raise SyntaxError('Something wrong with the format, eg. brackets are not closed')
                    #except SyntaxError:
                    #    print("something wrong! At file {} at line {}.".format(file_name, line_number))
                    #    raise
                readline = infile.readline()

        if (self.n_brackets != 0):
            try:
                raise SyntaxError('Something wrong with the format, eg. brackets are not closed')
            except SyntaxError:
                print("something wrong! At file {} at line {}.".format(file_name, line_number))
                raise

        return True
         
    def count_brackets(self, line):
        nbra = re.findall('{', line)
        nket = re.findall('}', line)
        self.n_brackets = self.n_brackets + len(nbra) - len(nket)

class Write:
    """print complete and incomplete data into output files"""

    def __init__ (self, args):
        for i in incomplete_ref_list : 
            if i.ref_type_ == 'control':
                args.output.write(i.all_ref_)
                args.output.write("\n")
            if i.ref_type_ == 'string':
                args.output.write(i.all_ref_)
                args.output.write("\n")
        for i in sorted (dictionary) : 
            args.output.write(dictionary[i].all_ref_)
            args.output.write("\n")
        incomplete_ref_list_remove_string = [i for i in incomplete_ref_list if i.ref_type_ != 'string' and i.ref_type_ != 'control']
        incomplete_ref_list_remove_string.sort(key = lambda i: i.ref_type_)
        if incomplete_ref_list_remove_string:
            print ('You have reference that do not contain all data. Please check "{}"'.format(args.error)) 
            for i in incomplete_ref_list_remove_string: 
                if i.ref_type_ != 'misc' and re.search('Necromancer', i.all_ref_, re.MULTILINE) == None:
                    args.error.write(i.all_ref_)
                    args.error.write("\n")
    

def main():
    """ 
        This script combines all input bibtex files into a user defined single file
        All references in the combined files are unique, and are labeled following the format of AUTHOR:YEAR:PAGE
        References with incomplete data are dumped into another user defined file 
        Usage:
             bibtex_combine [-h] [-o OUTPUT] [-e ERROR] input [input ...]
    """

    global args
    read = Read(args.input)
    write = Write(args)
    

parser = argparse.ArgumentParser(
        description="combine bibtex files and label references", 
        epilog="""
        This script combines all input bibtex files into a user defined single file.
        All references in the combined files are unique, and are labeled following the format of AUTHOR:YEAR:PAGE.
        References with incomplete data are dumped into another user defined file.
        """
)
parser.add_argument('input', nargs='+', help='Input files, the bibtex files that need processing')
parser.add_argument('-o', '--output', type=argparse.FileType('w'), default=sys.stdout, help='Output file, where combined and formatted reference exist')
parser.add_argument('-e', '--error', type=argparse.FileType('w'), default=sys.stdout, help='Error file,  where references with missing information get dumped')
args = parser.parse_args()

ref_list = []
incomplete_ref_list = []
seen_err_ref_list = []
dictionary = {}


if __name__ == '__main__':
  main()
